name: "Dressmaker's Studio"
favicon: null
layout_spectrum: 0.9961108462885022
typography_spectrum: 0.08293144288472831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25422263657674193
  lightness: 0.4548199602868408
  saturation: 0.45156628848053515
  rhythmicContrast: 0.6319302022457123
purpose: []
